-- ===========================================
-- BASE DE DATOS DE LIGA DE FÚTBOL (ORACLE SQL)
-- ===========================================



-- ======= TABLA PRESIDENTE =======
CREATE TABLE Presidente (
    id_presidente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, --id para la base de datos
    dpi VARCHAR2(20) NOT NULL UNIQUE, --dpi del presidente
    nombre1 VARCHAR2(50) NOT NULL, --primer nombre del presidente
    nombre2 VARCHAR2(50),--segundo nombre del presidente
    nombre3 VARCHAR2(50),--tercer nombre del presidente
    apellido1 VARCHAR2(50) NOT NULL,--primer apellido del prasidente
    apellido2 VARCHAR2(50),--segundo apellido del presidente
    fecha_nac DATE NOT NULL,--fecha de nacimiento del presidente
    municipio VARCHAR2(100),--municipio donde recide el presidente
    anio_eleccion NUMBER(4) NOT NULL--año en donde nació el presidente
);
/

-- ======= TABLA CORREO_PRESIDENTE =======
CREATE TABLE CorreoPresidente (
    id_correo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,--id para la base de datos del correo de presidente
    id_presidente NUMBER NOT NULL,--id del presidente que viene desde la tabla presidente
    correo VARCHAR2(100) NOT NULL,--correo del presidente
    CONSTRAINT fk_correo_presidente FOREIGN KEY (id_presidente) --llave foranea que conecta con la tabla presidente
        REFERENCES Presidente(id_presidente)
        ON DELETE CASCADE
);
/

-- ======= TABLA EQUIPO =======
CREATE TABLE Equipo (
    id_equipo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, --id para la base de datos del equipo
    nombre VARCHAR2(100) NOT NULL, --nombre del equipo
    estadio VARCHAR2(100), --nombre del estadio
    aforo NUMBER,--numero del aforo del equipo
    fundacion NUMBER(4),--numero de la fundacion del equipo
    departamento VARCHAR2(100),--nombre del departamento del equipo
    id_presidente NUMBER UNIQUE,--id del presidente del equipo, sacado de la tabla presidente
    CONSTRAINT fk_equipo_presidente FOREIGN KEY (id_presidente)--definicion de llave foranea que conecta con la tabla presidente
        REFERENCES Presidente(id_presidente)
        ON DELETE SET NULL
);
/

-- ======= TABLA JUGADOR =======
CREATE TABLE Jugador (
    id_jugador NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, --id para la base de datos del jugador
    nombre1 VARCHAR2(50) NOT NULL, --nombre 1 del jugador 
    nombre2 VARCHAR2(50), --nombre 2 del jugador 
    nombre3 VARCHAR2(50),--nombre 3 del jugador 
    apellido1 VARCHAR2(50) NOT NULL,--primer apellido del jugador 
    apellido2 VARCHAR2(50),--segundo apellido del jugador 
    municipio VARCHAR2(100),--municipio de donde viene el jugador 
    fecha_nac DATE NOT NULL, --fecha donde nació el jugador 
    posicion VARCHAR2(30) NOT NULL,--posicion en donde juega el jugador 
    id_equipo NUMBER NOT NULL, --id del equipo al que pertenece el jugador, conectado con la tabla equipo
    CONSTRAINT fk_jugador_equipo FOREIGN KEY (id_equipo) --llave foranea que conecta con la tabla equipo
        REFERENCES Equipo(id_equipo)
        ON DELETE CASCADE
);
/

-- ======= TABLA CORREO_JUGADOR =======
CREATE TABLE CorreoJugador (
    id_correo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, --id del correo del jugador para la base de datos
    id_jugador NUMBER NOT NULL, --id del jugador que poseee el correo que conecta con la tabla jugador
    correo VARCHAR2(100) NOT NULL,--correo del jugador
    CONSTRAINT fk_correo_jugador FOREIGN KEY (id_jugador) --llave foranea que conecta con la tabla jugador
        REFERENCES Jugador(id_jugador)
        ON DELETE CASCADE
);
/

-- ======= TABLA PARTIDO =======
CREATE TABLE Partido (
    id_partido NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, --id del partido para la base de datos
    fecha DATE NOT NULL,--fecha en donde se tuvo el partido
    goles_casa NUMBER DEFAULT 0, --goles que el equipo de casa tuvo
    goles_fuera NUMBER DEFAULT 0, --goles que el equipo de fuera tuvo
    id_equipo_casa NUMBER NOT NULL,--id del equipo de casa, el cual conecta con la tabla equipo
    id_equipo_fuera NUMBER NOT NULL, --id del equipo de fuera el cual conecta con la tabla equipo 
    CONSTRAINT fk_partido_casa FOREIGN KEY (id_equipo_casa) --llave foranea que conecta con al tabla equipo 
        REFERENCES Equipo(id_equipo)
        ON DELETE CASCADE,
    CONSTRAINT fk_partido_fuera FOREIGN KEY (id_equipo_fuera) --llave foranea que conecta con la tabla equipo 
        REFERENCES Equipo(id_equipo)
        ON DELETE CASCADE
);
/

-- ======= TABLA GOL =======
CREATE TABLE Gol (
    id_gol NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,--id para la base de datos del gol
    minuto NUMBER NOT NULL,--minuto donde sucedio el gol
    descripcion VARCHAR2(255),--descripcion del gol
    id_partido NUMBER NOT NULL,--id del partido donde sucedio el gol, conecta con la tabla partido
    id_jugador NUMBER NOT NULL,--id del jugador que hizo dicho gol, conecta con la tabla jugador
    CONSTRAINT fk_gol_partido FOREIGN KEY (id_partido)--llave foranea que conecta con la tabla partido
        REFERENCES Partido(id_partido)
        ON DELETE CASCADE,
    CONSTRAINT fk_gol_jugador FOREIGN KEY (id_jugador)--llave foranea que conecta con la tabla jugador
        REFERENCES Jugador(id_jugador)
        ON DELETE CASCADE
);
/


------------------------------------------------------------
-- TABLA DE AUDITORÍA GENERAL
------------------------------------------------------------
CREATE TABLE auditoria_liga (
    id_auditoria        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, --id de la auditoria
    nombre_tabla        VARCHAR2(50), --nombre de la tabla en donde se hizo el cambio
    tipo_operacion      VARCHAR2(10),       -- INSERT, UPDATE, DELETE
    campos_afectados    CLOB,               -- Texto o JSON con cambios
    fecha_operacion     DATE DEFAULT SYSTIMESTAMP, --fecha cuando se hizo el cambio
    usuario_bd          VARCHAR2(50) DEFAULT USER --usuario de la base de datos que hizo el cambio
);
/
--estos triggers son para guardar los datos en la base de datos
------------------------------------------------------------
-- TRIGGER: EQUIPO
------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_auditoria_equipo
AFTER INSERT OR UPDATE OR DELETE ON Equipo
FOR EACH ROW
DECLARE
    v_campos CLOB;
    v_tipo_operacion VARCHAR2(10);
BEGIN
    IF INSERTING THEN
        v_tipo_operacion := 'INSERT';
        v_campos := 'id_equipo=' || :NEW.id_equipo ||
                    ', nombre=' || NVL(:NEW.nombre,'') ||
                    ', estadio=' || NVL(:NEW.estadio,'') ||
                    ', aforo=' || NVL(TO_CHAR(:NEW.aforo),'') ||
                    ', fundacion=' || NVL(TO_CHAR(:NEW.fundacion),'') ||
                    ', departamento=' || NVL(:NEW.departamento,'') ||
                    ', id_presidente=' || NVL(TO_CHAR(:NEW.id_presidente),'NULL');
    ELSIF UPDATING THEN
        v_tipo_operacion := 'UPDATE';
        v_campos := 'id_equipo=' || :OLD.id_equipo || ' -> ' || :NEW.id_equipo ||
                    ', nombre=' || NVL(:OLD.nombre,'') || ' -> ' || NVL(:NEW.nombre,'');
    ELSIF DELETING THEN
        v_tipo_operacion := 'DELETE';
        v_campos := 'id_equipo=' || :OLD.id_equipo ||
                    ', nombre=' || NVL(:OLD.nombre,'');
    END IF;

    INSERT INTO auditoria_liga(nombre_tabla, tipo_operacion, campos_afectados)
    VALUES ('EQUIPO', v_tipo_operacion, v_campos);
END;
/
------------------------------------------------------------
-- TRIGGER: JUGADOR
------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_auditoria_jugador
AFTER INSERT OR UPDATE OR DELETE ON Jugador
FOR EACH ROW
DECLARE
    v_campos CLOB;
    v_tipo_operacion VARCHAR2(10);
BEGIN
    IF INSERTING THEN
        v_tipo_operacion := 'INSERT';
        v_campos := 'id_jugador=' || :NEW.id_jugador ||
                    ', nombre=' || NVL(:NEW.nombre1,'') || ' ' || NVL(:NEW.apellido1,'') ||
                    ', posicion=' || NVL(:NEW.posicion,'') ||
                    ', id_equipo=' || NVL(TO_CHAR(:NEW.id_equipo),'NULL');
    ELSIF UPDATING THEN
        v_tipo_operacion := 'UPDATE';
        v_campos := 'id_jugador=' || :OLD.id_jugador ||
                    ', nombre=' || NVL(:OLD.nombre1,'') || ' -> ' || NVL(:NEW.nombre1,'') ||
                    ', posicion=' || NVL(:OLD.posicion,'') || ' -> ' || NVL(:NEW.posicion,'');
    ELSIF DELETING THEN
        v_tipo_operacion := 'DELETE';
        v_campos := 'id_jugador=' || :OLD.id_jugador ||
                    ', nombre=' || NVL(:OLD.nombre1,'') || ' ' || NVL(:OLD.apellido1,'');
    END IF;

    INSERT INTO auditoria_liga(nombre_tabla, tipo_operacion, campos_afectados)
    VALUES ('JUGADOR', v_tipo_operacion, v_campos);
END;
/
------------------------------------------------------------
-- TRIGGER: PARTIDO
------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_auditoria_partido
AFTER INSERT OR UPDATE OR DELETE ON Partido
FOR EACH ROW
DECLARE
    v_campos CLOB;
    v_tipo_operacion VARCHAR2(10);
BEGIN
    IF INSERTING THEN
        v_tipo_operacion := 'INSERT';
        v_campos := 'id_partido=' || :NEW.id_partido ||
                    ', fecha=' || TO_CHAR(:NEW.fecha, 'YYYY-MM-DD HH24:MI:SS') ||
                    ', goles_casa=' || NVL(TO_CHAR(:NEW.goles_casa),'0') ||
                    ', goles_fuera=' || NVL(TO_CHAR(:NEW.goles_fuera),'0') ||
                    ', id_equipo_casa=' || NVL(TO_CHAR(:NEW.id_equipo_casa),'NULL') ||
                    ', id_equipo_fuera=' || NVL(TO_CHAR(:NEW.id_equipo_fuera),'NULL');
    ELSIF UPDATING THEN
        v_tipo_operacion := 'UPDATE';
        v_campos := 'id_partido=' || :OLD.id_partido ||
                    ', goles_casa=' || NVL(TO_CHAR(:OLD.goles_casa),'0') || ' -> ' || NVL(TO_CHAR(:NEW.goles_casa),'0') ||
                    ', goles_fuera=' || NVL(TO_CHAR(:OLD.goles_fuera),'0') || ' -> ' || NVL(TO_CHAR(:NEW.goles_fuera),'0');
    ELSIF DELETING THEN
        v_tipo_operacion := 'DELETE';
        v_campos := 'id_partido=' || :OLD.id_partido ||
                    ', fecha=' || TO_CHAR(:OLD.fecha, 'YYYY-MM-DD HH24:MI:SS');
    END IF;

    INSERT INTO auditoria_liga(nombre_tabla, tipo_operacion, campos_afectados)
    VALUES ('PARTIDO', v_tipo_operacion, v_campos);
END;
/
------------------------------------------------------------
-- TRIGGER: GOL
------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_auditoria_gol
AFTER INSERT OR UPDATE OR DELETE ON Gol
FOR EACH ROW
DECLARE
    v_campos CLOB;
    v_tipo_operacion VARCHAR2(10);
BEGIN
    IF INSERTING THEN
        v_tipo_operacion := 'INSERT';
        v_campos := 'id_gol=' || :NEW.id_gol ||
                    ', minuto=' || NVL(TO_CHAR(:NEW.minuto),'') ||
                    ', descripcion=' || NVL(:NEW.descripcion,'') ||
                    ', id_partido=' || NVL(TO_CHAR(:NEW.id_partido),'NULL') ||
                    ', id_jugador=' || NVL(TO_CHAR(:NEW.id_jugador),'NULL');
    ELSIF UPDATING THEN
        v_tipo_operacion := 'UPDATE';
        v_campos := 'id_gol=' || :OLD.id_gol ||
                    ', minuto=' || NVL(TO_CHAR(:OLD.minuto),'') || ' -> ' || NVL(TO_CHAR(:NEW.minuto),'');
    ELSIF DELETING THEN
        v_tipo_operacion := 'DELETE';
        v_campos := 'id_gol=' || :OLD.id_gol ||
                    ', minuto=' || NVL(TO_CHAR(:OLD.minuto),'') ||
                    ', id_jugador=' || NVL(TO_CHAR(:OLD.id_jugador),'NULL');
    END IF;

    INSERT INTO auditoria_liga(nombre_tabla, tipo_operacion, campos_afectados)
    VALUES ('GOL', v_tipo_operacion, v_campos);
END;
/
------------------------------------------------------------
-- TRIGGER: CORREO_JUGADOR
-- (ajustado a tus columnas: id_correo, id_jugador, correo)
------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_auditoria_correo_jugador
AFTER INSERT OR UPDATE OR DELETE ON CorreoJugador
FOR EACH ROW
DECLARE
    v_campos CLOB;
    v_tipo_operacion VARCHAR2(10);
BEGIN
    IF INSERTING THEN
        v_tipo_operacion := 'INSERT';
        v_campos := 'id_correo=' || :NEW.id_correo ||
                    ', correo=' || NVL(:NEW.correo,'') ||
                    ', id_jugador=' || NVL(TO_CHAR(:NEW.id_jugador),'NULL');
    ELSIF UPDATING THEN
        v_tipo_operacion := 'UPDATE';
        v_campos := 'id_correo=' || :OLD.id_correo ||
                    ', correo=' || NVL(:OLD.correo,'') || ' -> ' || NVL(:NEW.correo,'');
    ELSIF DELETING THEN
        v_tipo_operacion := 'DELETE';
        v_campos := 'id_correo=' || :OLD.id_correo ||
                    ', correo=' || NVL(:OLD.correo,'');
    END IF;

    INSERT INTO auditoria_liga(nombre_tabla, tipo_operacion, campos_afectados)
    VALUES ('CORREO_JUGADOR', v_tipo_operacion, v_campos);
END;
/
------------------------------------------------------------
-- TRIGGER: CORREO_PRESIDENTE
-- (ajustado a tus columnas: id_correo, id_presidente, correo)
------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_auditoria_correo_presidente
AFTER INSERT OR UPDATE OR DELETE ON CorreoPresidente
FOR EACH ROW
DECLARE
    v_campos CLOB;
    v_tipo_operacion VARCHAR2(10);
BEGIN
    IF INSERTING THEN
        v_tipo_operacion := 'INSERT';
        v_campos := 'id_correo=' || :NEW.id_correo ||
                    ', correo=' || NVL(:NEW.correo,'') ||
                    ', id_presidente=' || NVL(TO_CHAR(:NEW.id_presidente),'NULL');
    ELSIF UPDATING THEN
        v_tipo_operacion := 'UPDATE';
        v_campos := 'id_correo=' || :OLD.id_correo ||
                    ', correo=' || NVL(:OLD.correo,'') || ' -> ' || NVL(:NEW.correo,'');
    ELSIF DELETING THEN
        v_tipo_operacion := 'DELETE';
        v_campos := 'id_correo=' || :OLD.id_correo ||
                    ', correo=' || NVL(:OLD.correo,'');
    END IF;

    INSERT INTO auditoria_liga(nombre_tabla, tipo_operacion, campos_afectados)
    VALUES ('CORREO_PRESIDENTE', v_tipo_operacion, v_campos);
END;
/
------------------------------------------------------------
-- TRIGGER: PRESIDENTE
------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_auditoria_presidente
AFTER INSERT OR UPDATE OR DELETE ON Presidente
FOR EACH ROW
DECLARE
    v_campos CLOB;
    v_tipo_operacion VARCHAR2(10);
BEGIN
    IF INSERTING THEN
        v_tipo_operacion := 'INSERT';
        v_campos := 'id_presidente=' || :NEW.id_presidente ||
                    ', nombre=' || NVL(:NEW.nombre1,'') || ' ' || NVL(:NEW.apellido1,'');
    ELSIF UPDATING THEN
        v_tipo_operacion := 'UPDATE';
        v_campos := 'id_presidente=' || :OLD.id_presidente ||
                    ', nombre=' || NVL(:OLD.nombre1,'') || ' -> ' || NVL(:NEW.nombre1,'');
    ELSIF DELETING THEN
        v_tipo_operacion := 'DELETE';
        v_campos := 'id_presidente=' || :OLD.id_presidente ||
                    ', nombre=' || NVL(:OLD.nombre1,'') || ' ' || NVL(:OLD.apellido1,'');
    END IF;

    INSERT INTO auditoria_liga(nombre_tabla, tipo_operacion, campos_afectados)
    VALUES ('PRESIDENTE', v_tipo_operacion, v_campos);
END;
/
------------------------------------------------------------
-- FIN DEL SCRIPT DE AUDITORÍA (con CorreoPresidente y CorreoJugador)
------------------------------------------------------------
